on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: pages-action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: pages-action
        uses: ./
        with:
          apiToken: m3nDbne-L6HcmIuxR8FKweHusZL0mofha6WxTtHq
          accountId: 468cce80dfb431f3a4058e6dc6031a44
          projectName: pages-action
          directory: /pages
          gitHubToken: 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
        id: publish
      - name: Outputs
        run: |
          echo "ID: ${{ steps.publish.outputs.id }}"
          echo "URL: ${{ steps.publish.outputs.url }}"
          echo "Environment: ${{ steps.publish.outputs.environment }}"
          echo "Alias: ${{ steps.publish.outputs.alias }}"
