on: [push]

jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Example
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish to Cloudflare Pages
        uses: ./
        with:
          apiToken: 0557e30ef81c1a6ed445612a8d7818e20cc47
          accountId: 468cce80dfb431f3a4058e6dc6031a44
          projectName: github-actions
          directory: ./
          gitHubToken: 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
        id: publish
      - name: Outputs
        run: |
          echo "ID: ${{ steps.publish.outputs.id }}"
          echo "URL: ${{ steps.publish.outputs.url }}"
          echo "Environment: .env
          echo "Alias: ${{ steps.publish.outputs.alias }}"
